### ISSUE TITLE
Implement local identity

### ISSUE THREAD

**Issue by raed667** [RaedsLab/EncryptedWebRTChatter#1]
A p2p identity system should be implemented. This system should associate a publicKey with a username. 

When a new connection is established, the users exchange and store both publicKeys and usernames.

A user should be able to generate a new identity when starting a new conversation. 

If a user receives a public key with a username that he already has stored, we compare the public keys and display a warning if they don't match.

**Comment by RaedsLab** [comment]
TimeLine : Integration by Sunday 05/06/16

**Comment by raed667** [comment]
Basic initial setup: fea85c7e1566a6179dc612663e1b3fdef21db081 

To be tested
